services:
  _defaults:
    public: true

  prestashop.module.b2bwholesale.form.identifiable_object.data_provider.activity_type_form_data_provider:
    class: 'PrestaShop\Module\B2BWholesale\Form\DataProvider\ActivityTypeFormDataProvider'
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'
