services:
  _defaults:
    public: true

  prestashop.module.b2bwholesale.form.identifiable_object.data_handler.activity_type_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    public: true
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@prestashop.module.b2bwholesale.form.identifiable_object.data_handler.activity_type_form_data_handler'
