services:
  _defaults:
    public: true

  # grid
  prestashop.core.grid.definition.factory.activity_type_definition_factory:
    class: 'PrestaShop\Module\B2BWholesale\Core\Grid\Definition\Factory\ActivityTypeGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  # ActivityTypeQueryBuilder
  prestashop.core.grid.query.activity_type_query_builder:
    class: 'PrestaShop\Module\B2BWholesale\Core\Grid\Query\ActivityTypeQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
    public: true

  # Configure our Grid Data factory to use the query builder that we registered above
  prestashop.core.grid.data.factory.activity_type_query_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@prestashop.core.grid.query.activity_type_query_builder' # service id of our query builder
      - '@prestashop.core.hook.dispatcher' # every doctrine query builder needs the hook dispatcher
      - '@prestashop.core.grid.query.doctrine_query_parser' # parser to get the raw SQL query
      - 'activity_types' # this should match your grid id, in our case it's "products"

  # Configure Grid factory to use services we have implemented
  prestashop.core.grid.activity_type_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.core.grid.definition.factory.activity_type_definition_factory' # our definition factory
      - '@prestashop.core.grid.data.factory.activity_type_query_data_factory'              # our data factory
      - '@prestashop.core.grid.filter.form_factory'                            # core service needed by grid factory
      - '@prestashop.core.hook.dispatcher'                                     # core service needed by grid factory

  prestashop.core.form.identifiable_object.data_provider.activity_type_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ManufacturerFormDataProvider'
    arguments:
      - '@prestashop.core.command_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'
